name: title_bar
description: Flutter plugin for changing title_bar on go-flutter
author: zephylac
homepage: https://github.com/zephylac/title_bar/
repository: https://github.com/zephylac/title_bar/
issue_tracker: https://github.com/zephylac/title_bar/issues/
version: 0.1.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.1.0 <3.0.0"